# import helper library
import logging
import os
from twilio.rest import Client

logger = logging.getLogger(__name__)

# turn into a function that can be called from the main.py file to make a call to a phone number using Twilio API
def make_twilio_call(to_number, from_number, media_url=None):
    account_sid = os.environ.get("TWILIO_ACCOUNT_SID")
    auth_token = os.environ.get("TWILIO_AUTH_TOKEN")
    if not account_sid or not auth_token:
        raise ValueError("TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN environment variables are required for Twilio media streaming")

    media_url = media_url or os.environ.get("TWILIO_MEDIA_WS_URL")
    if not media_url:
        raise ValueError("TWILIO_MEDIA_WS_URL environment variable is required for Twilio media streaming")

    client = Client(account_sid, auth_token)
    logger.info(f"make_twilio_call using media_url={media_url} to={to_number} from={from_number}")

    # IMPORTANT: <Start><Stream> is unidirectional — Twilio will forward the
    # caller's audio to your websocket, but it will NEVER play back anything
    # you send over that same websocket. That's why audio generated by Gemini
    # was reaching Twilio (confirmed in logs) but the caller never heard it:
    # <Start><Stream> simply has no mechanism to play media back into the call.
    #
    # <Connect><Stream> is bidirectional: Twilio will play any "media" events
    # your websocket sends back into the live call. <Connect> also blocks and
    # holds the call open on its own (the call ends when the websocket closes
    # or the call is hung up), so the old <Say>/<Pause length="3600"> workaround
    # is no longer needed. This was my main mistake.
    twiml = (
        f'<Response>'
        f'<Connect>'
        f'<Stream url="{media_url}"/>'
        f'</Connect>'
        f'</Response>'
    )

    call = client.calls.create(
        to=to_number,
        from_=from_number,
        twiml=twiml,
    )

    print(call.sid)
    return call.sid

if __name__ == "__main__":
    #test the function
    make_twilio_call("+15719778953", "+18338593215")